Source/Controllers/GooglePayController.cs
namespace GooglePay.Shop.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    [ApiExplorerSettings(IgnoreApi = true)]
    public class GooglePayController : Controller
    {
        [Route("")]
        [Route("Sale")]
        public IActionResult Sale()
        {
            return View();
        }

        [Route("Authorization")]
        public IActionResult Authorization()
        {
            return View();
        }

        [Route("Decryption")]
        public IActionResult Decryption()
        {
            return View();
        }
    }
}

Source/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GooglePay.Shop | @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GooglePay.Shop.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="~/src/icon.ico">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"/>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" id="navigationGooglePaySale" asp-area="" asp-controller="GooglePay" asp-action="Sale">GooglePay Sale</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" id="navigationGooglePayAuthorization" asp-area="" asp-controller="GooglePay" asp-action="Authorization">GooglePay Authorization</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" id="navigationGooglePayDecryption" asp-area="" asp-controller="GooglePay" asp-action="Decryption">GooglePay Decryption</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" id="navigationGooglePayDecryptionSwagger" href="/swagger/index.html">GooglePay Decryption API Swagger</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">&copy; 2024 - <a href="https://github.com/lyndychivs/GooglePay.Shop" target="_blank">lyndychivs.GooglePay.Shop</a></div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>